# Generated by Django 2.2 on 2020-09-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('photo', models.ImageField(max_length=255, null=True, upload_to='Child/', verbose_name='写真')),
            ],
            options={
                'db_table': 'cuser',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('photo', models.ImageField(max_length=255, null=True, upload_to='parent/', verbose_name='写真')),
            ],
            options={
                'db_table': 'puser',
            },
        ),
        migrations.CreateModel(
            name='Ticket_holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('used_flg', models.IntegerField(default=0, verbose_name='利用フラグ')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Child', verbose_name='子ユーザーid')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='チケットID')),
            ],
            options={
                'db_table': 'ticket_holding',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('status', models.IntegerField(default=1, verbose_name='ステータス')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Child', verbose_name='子ユーザーID')),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Parent', verbose_name='親ユーザーID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='タスクID')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('ymd', models.DateTimeField(verbose_name='入出金日時')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='金額')),
                ('kind', models.IntegerField(verbose_name='取引種類')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Child', verbose_name='子ユーザーID')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.Task', verbose_name='タスクID')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.Ticket', verbose_name='チケットID')),
                ('ticket_holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Ticket_holding', verbose_name='保有チケットID')),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='puser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Parent', verbose_name='親ユーザーID'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('balance', models.IntegerField(default=0, verbose_name='残高')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Child', verbose_name='子ユーザーID')),
            ],
            options={
                'db_table': 'balance',
            },
        ),
    ]
