# Generated by Django 2.2 on 2020-07-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('photo', models.CharField(max_length=255, verbose_name='写真')),
            ],
            options={
                'db_table': 'cuser',
            },
        ),
    ]
