# Generated by Django 2.2 on 2026-05-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260504_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='task_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='タスク名'),
        ),
        migrations.AddField(
            model_name='history',
            name='ticket_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='チケット名'),
        ),
    ]
