# Generated by Django 2.2 on 2020-07-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='cuser_id',
            new_name='cuser',
        ),
    ]
