# Generated by Django 2.2 on 2020-07-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_child_puser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='写真'),
        ),
    ]
