# Generated by Django 2.2 on 2020-07-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20200708_2123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20200708_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('used_flg', models.IntegerField(default=0, verbose_name='利用フラグ')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Balance', verbose_name='残高id')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='チケットID')),
            ],
            options={
                'db_table': 'ticket_holding',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('status', models.CharField(max_length=255, verbose_name='ステータス')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Child', verbose_name='子ユーザーID')),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='親ユーザーID')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('ymd', models.DateTimeField(verbose_name='入出金日時')),
                ('amount', models.IntegerField(default=0, verbose_name='金額')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Balance', verbose_name='残高id')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='チケットID')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
