# Generated by Django 2.2 on 2020-07-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('users', '0007_history_request_ticket_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='balance',
        ),
        migrations.AddField(
            model_name='history',
            name='task',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='タスクID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='task',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='タスクID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='child/', verbose_name='写真'),
        ),
        migrations.CreateModel(
            name='History_ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('ymd', models.DateTimeField(verbose_name='入出金日時')),
                ('ticket_holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Ticket_holding', verbose_name='チケット保有ID')),
            ],
            options={
                'db_table': 'history_ticket',
            },
        ),
    ]
