# Generated by Django 2.2 on 2020-07-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200724_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='cuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Child', verbose_name='子ユーザーID'),
            preserve_default=False,
        ),
    ]
