# Generated by Django 2.2 on 2020-07-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_history_cuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to='Child/', verbose_name='写真'),
        ),
    ]
