# Generated by Django 2.2 on 2020-07-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200727_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='タスクID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='チケットID'),
        ),
    ]
