# Generated by Django 2.2 on 2020-07-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200728_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Child', verbose_name='子ユーザーID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.Task', verbose_name='タスクID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.Ticket', verbose_name='チケットID'),
        ),
    ]
