# Generated by Django 2.2 on 2020-07-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200728_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(default=1, verbose_name='ステータス'),
        ),
    ]
