# Generated by Django 2.2 on 2020-07-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200728_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.Task', verbose_name='タスクID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.Ticket', verbose_name='チケットID'),
        ),
    ]
