# Generated by Django 2.2 on 2020-08-03 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200729_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_holding',
            name='balance',
        ),
        migrations.AddField(
            model_name='ticket_holding',
            name='cuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Child', verbose_name='子ユーザーid'),
            preserve_default=False,
        ),
    ]
