# Generated by Django 2.2 on 2020-08-05 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200804_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='kind',
            field=models.IntegerField(default=0, verbose_name='取引種類'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='ticket_holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Ticket_holding', verbose_name='保有チケットID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額'),
        ),
        migrations.DeleteModel(
            name='History_ticket',
        ),
    ]
