# Generated by Django 2.2 on 2020-08-10 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200805_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ticket_holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Ticket_holding', verbose_name='保有チケットID'),
        ),
    ]
