# Generated by Django 2.2 on 2020-08-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200810_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Child', verbose_name='子ユーザーID'),
        ),
    ]
