# Generated by Django 2.2 on 2020-08-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_auto_20200805_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('summary_ym', models.CharField(max_length=6, unique=True, verbose_name='年月')),
                ('count', models.IntegerField(default=0, verbose_name='取引件数')),
                ('price', models.IntegerField(default=0, verbose_name='取引金額')),
            ],
            options={
                'db_table': 'monthly_summary',
            },
        ),
        migrations.CreateModel(
            name='MonthlyChildSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('summary_ym', models.CharField(max_length=6, verbose_name='年月')),
                ('count', models.IntegerField(default=0, verbose_name='取引件数')),
                ('price', models.IntegerField(default=0, verbose_name='取引金額')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Child', verbose_name='子ユーザーID')),
            ],
            options={
                'db_table': 'monthly_child_summary',
                'unique_together': {('summary_ym', 'cuser')},
            },
        ),
    ]
