# Generated by Django 2.2 on 2020-07-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200708_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to='', verbose_name='写真'),
        ),
    ]
