# Generated by Django 2.2 on 2020-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200715_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to='parent/', verbose_name='写真'),
        ),
    ]
