# Generated by Django 2.2 on 2020-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('task_name', models.CharField(max_length=255, verbose_name='タスク名')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
