# Generated by Django 2.2 on 2020-07-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
